"""
Seed script to populate the database with demo profiles for development/testing.
Usage: python seed.py
"""
import asyncio
from app.database import engine, async_session, Base
from app.models.user import User
from app.models.profile import Profile
from app.models.badge import Badge
from app.auth.jwt import hash_password

DEMO_PROFILES = [
    {
        "email": "alex.chen@demo.dev",
        "password": "password123",
        "profile": {
            "display_name": "Alex Chen",
            "age": 28,
            "gender": "Male",
            "looking_for": ["Female", "Non-binary"],
            "bio": "Full-stack engineer who loves building developer tools. Currently obsessed with Rust and WebAssembly. I believe the best code is the code you don't have to write.",
            "city": "San Francisco",
            "state": "California",
            "country": "United States",
            "role": "Full Stack Engineer",
            "years_experience": 6,
            "company": "Vercel",
            "tech_stack": ["TypeScript", "React", "Next.js", "Node.js", "Rust", "PostgreSQL", "Docker", "AWS"],
            "favorite_tools": ["VS Code", "Warp", "Figma", "GitHub Copilot", "Linear"],
            "work_style": "Remote",
            "github_url": "https://github.com/alexchen",
            "personality": "Builder",
            "hobbies": ["open source", "rock climbing", "mechanical keyboards"],
            "matching_mode": "Serious Relationship",
            "prompt_tabs_open": "GitHub PR reviews, Rust docs, that one Stack Overflow question from 2014 that somehow still saves me",
            "prompt_toxic_trait": "I rewrite the entire codebase when I join a new team",
            "prompt_hill_to_die_on": "TypeScript is not optional. If you're writing plain JS in 2024, we need to talk.",
            "github_languages": ["TypeScript", "Rust", "JavaScript", "Go", "Python"],
            "github_repos_count": 47,
        },
        "badges": ["Open Source Contributor", "Polyglot Developer", "Profile Complete"],
    },
    {
        "email": "priya.sharma@demo.dev",
        "password": "password123",
        "profile": {
            "display_name": "Priya Sharma",
            "age": 26,
            "gender": "Female",
            "looking_for": ["Male"],
            "bio": "QA engineer by day, game dev by night. I break things professionally and fix them recreationally. Playwright enthusiast and proud test pyramid defender.",
            "city": "Austin",
            "state": "Texas",
            "country": "United States",
            "role": "SDET / QA Engineer",
            "years_experience": 4,
            "company": "Stripe",
            "tech_stack": ["Python", "Playwright", "Cypress", "Jest", "TypeScript", "Docker", "Kubernetes", "AWS"],
            "favorite_tools": ["IntelliJ IDEA", "Postman", "Docker Desktop", "Notion", "Slack"],
            "work_style": "Hybrid",
            "personality": "Researcher",
            "hobbies": ["indie game dev", "hiking", "anime", "board games"],
            "matching_mode": "Serious Relationship",
            "prompt_tabs_open": "Playwright docs, a Jira board with 47 bugs, and YouTube playing lo-fi beats",
            "prompt_toxic_trait": "I write tests for other people's tests. Test the tests!",
            "prompt_hill_to_die_on": "If it's not tested, it doesn't work. I don't care if it 'runs on your machine'.",
            "github_languages": ["Python", "TypeScript", "JavaScript", "C#"],
            "github_repos_count": 23,
        },
        "badges": ["Bug Slayer", "Profile Complete"],
    },
    {
        "email": "jordan.williams@demo.dev",
        "password": "password123",
        "profile": {
            "display_name": "Jordan Williams",
            "age": 31,
            "gender": "Non-binary",
            "looking_for": ["Male", "Female", "Non-binary"],
            "bio": "Staff engineer at a startup that's somehow still alive. I architect systems during the day and mentor juniors in the evening. Big fan of boring technology.",
            "city": "Seattle",
            "state": "Washington",
            "country": "United States",
            "role": "Backend Engineer",
            "years_experience": 10,
            "company": "Datadog",
            "tech_stack": ["Go", "Python", "PostgreSQL", "Redis", "Kafka", "Kubernetes", "Terraform", "AWS", "gRPC"],
            "favorite_tools": ["Neovim", "iTerm2", "Linear", "Grafana"],
            "work_style": "Remote",
            "personality": "Mentor",
            "hobbies": ["mentoring", "writing technical blogs", "cooking", "cycling"],
            "matching_mode": "Serious Relationship",
            "prompt_tabs_open": "Grafana dashboards, a Notion doc about system design patterns, and a recipe for shakshuka",
            "prompt_toxic_trait": "I say 'it depends' in every technical discussion",
            "prompt_hill_to_die_on": "Microservices are a mistake for 90% of companies. Monolith first, always.",
            "github_languages": ["Go", "Python", "Rust", "Shell", "HCL"],
            "github_repos_count": 62,
        },
        "badges": ["Senior Dev Mode", "Open Source Contributor", "Polyglot Developer", "Profile Complete", "Conversation Starter"],
    },
    {
        "email": "maya.rodriguez@demo.dev",
        "password": "password123",
        "profile": {
            "display_name": "Maya Rodriguez",
            "age": 25,
            "gender": "Female",
            "looking_for": ["Male", "Female"],
            "bio": "Frontend engineer obsessed with animations and micro-interactions. I believe great UX is a superpower. Currently exploring the intersection of design and engineering.",
            "city": "New York",
            "state": "New York",
            "country": "United States",
            "role": "Frontend Engineer",
            "years_experience": 3,
            "company": "Figma",
            "tech_stack": ["React", "TypeScript", "Next.js", "Tailwind", "CSS", "JavaScript", "GraphQL", "Svelte"],
            "favorite_tools": ["VS Code", "Figma", "GitHub Copilot", "Notion", "Warp"],
            "work_style": "Hybrid",
            "personality": "Extrovert",
            "hobbies": ["UI design", "photography", "coffee tasting", "salsa dancing"],
            "matching_mode": "Serious Relationship",
            "prompt_tabs_open": "Dribbble, CSS-Tricks, 14 CodePen experiments, and a Spotify playlist called 'Code Flow'",
            "prompt_toxic_trait": "I spend 4 hours on a button animation that nobody will notice",
            "prompt_hill_to_die_on": "CSS is a real programming language and I will fight anyone who says otherwise.",
            "github_languages": ["TypeScript", "JavaScript", "CSS", "HTML", "Svelte"],
            "github_repos_count": 31,
        },
        "badges": ["Profile Complete", "Early Adopter"],
    },
    {
        "email": "sam.nakamura@demo.dev",
        "password": "password123",
        "profile": {
            "display_name": "Sam Nakamura",
            "age": 29,
            "gender": "Male",
            "looking_for": ["Female", "Non-binary"],
            "bio": "ML engineer building recommendation systems. I train models during the day and train for marathons in the morning. Looking for someone who appreciates both gradient descent and hiking uphill.",
            "city": "Portland",
            "state": "Oregon",
            "country": "United States",
            "role": "ML Engineer",
            "years_experience": 5,
            "company": "Netflix",
            "tech_stack": ["Python", "PyTorch", "TensorFlow", "Pandas", "SQL", "Spark", "Docker", "AWS", "Kubernetes"],
            "favorite_tools": ["VS Code", "Jupyter", "Docker Desktop", "Notion"],
            "work_style": "Flexible",
            "personality": "Introvert",
            "hobbies": ["running", "reading sci-fi", "cooking", "kaggle competitions"],
            "matching_mode": "Serious Relationship",
            "prompt_tabs_open": "arxiv papers I'll never finish reading, a Jupyter notebook with 200 cells, and Weather.com",
            "prompt_toxic_trait": "I call everything 'AI' in demos even when it's just an if-else statement",
            "prompt_hill_to_die_on": "Most ML problems can be solved with logistic regression. You don't need a transformer for everything.",
            "github_languages": ["Python", "Jupyter Notebook", "R", "Shell", "SQL"],
            "github_repos_count": 28,
        },
        "badges": ["Polyglot Developer", "Profile Complete"],
    },
    {
        "email": "kai.oconnor@demo.dev",
        "password": "password123",
        "profile": {
            "display_name": "Kai O'Connor",
            "age": 27,
            "gender": "Male",
            "looking_for": ["Male"],
            "bio": "DevOps engineer and infrastructure nerd. I make pipelines go brrr. If your deployment takes more than 5 minutes, we should talk. Not about dating — about your CI/CD.",
            "city": "Denver",
            "state": "Colorado",
            "country": "United States",
            "role": "DevOps Engineer",
            "years_experience": 5,
            "company": "HashiCorp",
            "tech_stack": ["Terraform", "Kubernetes", "Docker", "AWS", "GCP", "Python", "Go", "Linux", "GitHub Actions"],
            "favorite_tools": ["Neovim", "iTerm2", "Docker Desktop", "Slack"],
            "work_style": "Remote",
            "personality": "Builder",
            "hobbies": ["homelab", "snowboarding", "craft beer", "self-hosting everything"],
            "matching_mode": "Serious Relationship",
            "prompt_tabs_open": "Terraform docs, a failing GitHub Actions workflow, and r/homelab",
            "prompt_toxic_trait": "I containerize everything. My grocery list runs in a Docker container.",
            "prompt_hill_to_die_on": "YAML is not a programming language and should never have been used for CI/CD configs.",
            "github_languages": ["Go", "Python", "HCL", "Shell", "Dockerfile"],
            "github_repos_count": 35,
        },
        "badges": ["CI/CD Champion", "Open Source Contributor", "Profile Complete"],
    },
    {
        "email": "elena.petrov@demo.dev",
        "password": "password123",
        "profile": {
            "display_name": "Elena Petrov",
            "age": 30,
            "gender": "Female",
            "looking_for": ["Male"],
            "bio": "Security engineer and former CTF champion. I find vulnerabilities in your code and in my own heart. Looking for someone whose passwords are as strong as their sense of humor.",
            "city": "Chicago",
            "state": "Illinois",
            "country": "United States",
            "role": "Security Engineer",
            "years_experience": 7,
            "company": "CrowdStrike",
            "tech_stack": ["Python", "Rust", "Go", "Linux", "Docker", "AWS", "Terraform"],
            "favorite_tools": ["Neovim", "iTerm2", "Burp Suite"],
            "work_style": "Hybrid",
            "personality": "Researcher",
            "hobbies": ["CTF competitions", "lockpicking", "chess", "true crime podcasts"],
            "matching_mode": "Serious Relationship",
            "prompt_tabs_open": "HackerOne reports, OWASP cheat sheets, and a chess.com game I'm losing",
            "prompt_toxic_trait": "I pentest my friends' side projects without asking",
            "prompt_hill_to_die_on": "If you store passwords in plain text, you deserve the breach.",
            "github_languages": ["Python", "Rust", "Go", "C", "Shell"],
            "github_repos_count": 19,
        },
        "badges": ["Polyglot Developer", "Profile Complete"],
    },
    {
        "email": "marcus.johnson@demo.dev",
        "password": "password123",
        "profile": {
            "display_name": "Marcus Johnson",
            "age": 33,
            "gender": "Male",
            "looking_for": ["Female"],
            "bio": "Tech founder on my third startup. First one failed, second got acqui-hired, third time's the charm. Looking for a co-founder or a life partner — ideally both.",
            "city": "San Francisco",
            "state": "California",
            "country": "United States",
            "role": "Tech Founder",
            "years_experience": 12,
            "company": "Stealth Startup",
            "tech_stack": ["Python", "React", "TypeScript", "PostgreSQL", "Docker", "AWS", "Redis", "FastAPI"],
            "favorite_tools": ["VS Code", "Linear", "Notion", "Figma", "Slack"],
            "work_style": "Onsite",
            "personality": "Extrovert",
            "hobbies": ["startups", "angel investing", "surfing", "reading business books"],
            "matching_mode": "Co-founder Energy",
            "prompt_tabs_open": "YC application, pitch deck v47, and 'how to make ramen profitable' Google search",
            "prompt_toxic_trait": "I pivot the product every time I talk to a new user",
            "prompt_hill_to_die_on": "Most SaaS products could be a spreadsheet. Including the one I'm building.",
            "github_languages": ["Python", "TypeScript", "JavaScript", "Shell"],
            "github_repos_count": 15,
        },
        "badges": ["Senior Dev Mode", "Profile Complete", "Early Adopter"],
    },
    {
        "email": "luna.tran@demo.dev",
        "password": "password123",
        "profile": {
            "display_name": "Luna Tran",
            "age": 24,
            "gender": "Female",
            "looking_for": ["Male", "Female"],
            "bio": "Mobile engineer who switched from iOS to Flutter and never looked back. Side project addict with 12 unfinished apps on my phone. Let's build something together (or at least finish one thing).",
            "city": "Los Angeles",
            "state": "California",
            "country": "United States",
            "role": "Mobile Engineer",
            "years_experience": 2,
            "company": "Spotify",
            "tech_stack": ["Flutter", "Kotlin", "Swift", "TypeScript", "React Native", "Firebase"],
            "favorite_tools": ["VS Code", "Figma", "Notion", "GitHub Copilot"],
            "work_style": "Hybrid",
            "personality": "Ambivert",
            "hobbies": ["mobile app design", "digital art", "yoga", "boba tea hunting"],
            "matching_mode": "Casual",
            "prompt_tabs_open": "Flutter docs, 3 app ideas in Notion, Apple developer forums, and a boba menu",
            "prompt_toxic_trait": "I start a new side project every weekend and abandon it by Monday",
            "prompt_hill_to_die_on": "Cross-platform frameworks are the future. Native is dead (please don't @ me).",
            "github_languages": ["Dart", "Kotlin", "Swift", "TypeScript", "JavaScript"],
            "github_repos_count": 34,
        },
        "badges": ["Polyglot Developer", "Profile Complete"],
    },
    {
        "email": "derek.kim@demo.dev",
        "password": "password123",
        "profile": {
            "display_name": "Derek Kim",
            "age": 27,
            "gender": "Male",
            "looking_for": ["Female"],
            "bio": "Data engineer who loves building pipelines and breaking down silos. If your data warehouse is a mess, I'm your person. Also makes a mean pour-over coffee.",
            "city": "Austin",
            "state": "Texas",
            "country": "United States",
            "role": "Data Engineer",
            "years_experience": 4,
            "company": "Databricks",
            "tech_stack": ["Python", "Spark", "SQL", "Kafka", "Airflow", "dbt", "PostgreSQL", "AWS", "Docker"],
            "favorite_tools": ["VS Code", "Docker Desktop", "Notion", "Slack"],
            "work_style": "Remote",
            "personality": "Introvert",
            "hobbies": ["coffee", "data visualization", "piano", "hiking"],
            "matching_mode": "Serious Relationship",
            "prompt_tabs_open": "Airflow DAG logs, a dbt model with 47 CTEs, and 'best pour-over technique' on YouTube",
            "prompt_toxic_trait": "I judge people by their SQL formatting",
            "prompt_hill_to_die_on": "If you're writing SELECT *, you've already lost.",
            "github_languages": ["Python", "SQL", "Shell", "HCL"],
            "github_repos_count": 16,
        },
        "badges": ["Profile Complete"],
    },
    {
        "email": "riley.foster@demo.dev",
        "password": "password123",
        "profile": {
            "display_name": "Riley Foster",
            "age": 26,
            "gender": "Non-binary",
            "looking_for": ["Male", "Female", "Non-binary"],
            "bio": "Product engineer who cares way too much about user experience. I write code that humans actually want to use. Accessibility advocate. Will judge your app's tab order.",
            "city": "Brooklyn",
            "state": "New York",
            "country": "United States",
            "role": "Product Engineer",
            "years_experience": 4,
            "company": "Linear",
            "tech_stack": ["TypeScript", "React", "Next.js", "Node.js", "PostgreSQL", "Tailwind", "GraphQL"],
            "favorite_tools": ["VS Code", "Figma", "Linear", "GitHub Copilot", "Notion"],
            "work_style": "Remote",
            "personality": "Builder",
            "hobbies": ["accessibility advocacy", "design systems", "journaling", "vinyl records"],
            "matching_mode": "Serious Relationship",
            "prompt_tabs_open": "WCAG guidelines, a Figma prototype, three PR reviews, and Bandcamp",
            "prompt_toxic_trait": "I redesign every app I use and send unsolicited feedback to the founders",
            "prompt_hill_to_die_on": "If your app isn't accessible, it's not done. Period.",
            "github_languages": ["TypeScript", "JavaScript", "CSS", "MDX"],
            "github_repos_count": 22,
        },
        "badges": ["Profile Complete", "Early Adopter"],
    },
    {
        "email": "sophie.larsson@demo.dev",
        "password": "password123",
        "profile": {
            "display_name": "Sophie Larsson",
            "age": 29,
            "gender": "Female",
            "looking_for": ["Male"],
            "bio": "Backend engineer who dreams in SQL. I optimize queries for fun and migrate databases for therapy. Currently learning Rust because apparently I enjoy suffering.",
            "city": "Seattle",
            "state": "Washington",
            "country": "United States",
            "role": "Backend Engineer",
            "years_experience": 6,
            "company": "Shopify",
            "tech_stack": ["Ruby", "Rails", "PostgreSQL", "Redis", "GraphQL", "Docker", "Kubernetes", "Rust"],
            "favorite_tools": ["Neovim", "iTerm2", "Postman", "Notion"],
            "work_style": "Remote",
            "personality": "Introvert",
            "hobbies": ["reading", "baking sourdough", "crossword puzzles", "cat parenting"],
            "matching_mode": "Serious Relationship",
            "prompt_tabs_open": "PostgreSQL EXPLAIN ANALYZE output, the Rust Book chapter 10 (again), and a sourdough recipe",
            "prompt_toxic_trait": "I optimize SQL queries that run once a month and take 200ms",
            "prompt_hill_to_die_on": "ORMs are training wheels. Write your own SQL like an adult.",
            "github_languages": ["Ruby", "Rust", "SQL", "Python", "Shell"],
            "github_repos_count": 29,
        },
        "badges": ["Polyglot Developer", "Profile Complete"],
    },
]


async def seed():
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.drop_all)
        await conn.run_sync(Base.metadata.create_all)

    async with async_session() as db:
        for demo in DEMO_PROFILES:
            # Create user
            user = User(
                email=demo["email"],
                password_hash=hash_password(demo["password"]),
                is_verified=True,
                is_active=True,
            )
            db.add(user)
            await db.flush()

            # Create profile
            profile_data = demo["profile"]
            profile = Profile(user_id=user.id, **profile_data)
            db.add(profile)

            # Create badges
            for badge_type in demo.get("badges", []):
                badge = Badge(user_id=user.id, badge_type=badge_type)
                db.add(badge)

        await db.commit()

    print(f"Seeded {len(DEMO_PROFILES)} demo profiles successfully!")
    print("\nDemo accounts (all use password 'password123'):")
    for demo in DEMO_PROFILES:
        p = demo["profile"]
        print(f"  {demo['email']:35s} — {p['display_name']} ({p['role']}, {p['city']})")


if __name__ == "__main__":
    asyncio.run(seed())
